### ISSUE TITLE
Investigate "Communication" Feature

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#3]
Make a wiki page for and research the "Communication" features. Mock ups? Collaborate with [news feed](https://github.com/opencms/opencms/issues/2) feature.

**Comment by zdwolfe** [comment]
@nbuhay on [eeba39ac6c...](https://github.com/opencms/opencms/wiki/Communication/eeba39ac6c4ad838a6173405fe82caf81a5622b5), is that widget to be placed on a student's home page? Would you expect something like this to be available for instructors as well?

**Comment by nbuhay** [comment]
Yes, my idea was that this widget would immediately be available on the homepage.  I figured there easily could be a professor one as well.  There would be a few differences with the prof one though such as an option to message all or certain classes and say "class is canceled because I am sick" or so.  Still thinking on it.

**Comment by zdwolfe** [comment]
@nbuhay good idea with the multi-class messaging. Would a per-class widget be useful too? In your mockup there's a dropdown to select a class - would it make sense to put the widget in the class' page as well?

**Comment by nbuhay** [comment]
I think that's a good idea for the widget per class.  Maybe when you are in a specific course's content the default info for that course will be loaded into the widget.

**Comment by zdwolfe** [comment]
Yeah I agree.
